name: Build
on: workflow_dispatch

jobs:
  build_matrix:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        node-version: [14]
        config:
          - { os: macos-latest, arch: x64 }
          - { os: ubuntu-latest, arch: x64 }
          - { os: windows-latest, arch: x64 }
          - { os: windows-latest, arch: ia32 }
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run prebuild
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: prebuilds

  build:
    runs-on: ubuntu-latest
    needs: build_matrix
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: prebuilds
    - run: ls -laR prebuilds
